#!/usr/bin/env python3
"""Probe a repository and generate a project-local AGENTS starter without overwriting files."""
from __future__ import annotations
import argparse,json,os,re,subprocess
from pathlib import Path

SKIP={'.git','node_modules','.venv','venv','dist','build','.next','.output','target','vendor'}

def read_json(p):
    try:return json.loads(p.read_text(encoding='utf-8'))
    except Exception:return {}

def main():
    ap=argparse.ArgumentParser(description=__doc__); ap.add_argument('repository',type=Path); ap.add_argument('--output',type=Path)
    args=ap.parse_args(); repo=args.repository.resolve(); out=(args.output or repo/'.agents/PROJECT-PROBE.json').resolve()
    manifests=[]; commands={}; agents=[]; risks=[]
    for base,dirs,files in os.walk(repo):
        dirs[:]=[d for d in dirs if d not in SKIP]
        b=Path(base)
        for f in files:
            p=b/f
            rel=p.relative_to(repo).as_posix()
            if f in ('AGENTS.md','CLAUDE.md','GEMINI.md'): agents.append(rel)
            if f=='package.json':
                data=read_json(p); manifests.append(rel)
                for k,v in data.get('scripts',{}).items(): commands[f'{rel}:{k}']=v
            elif f in ('pyproject.toml','Cargo.toml','go.mod','pom.xml','build.gradle','Makefile','justfile'):
                manifests.append(rel)
            if f.lower() in ('agents.md','readme.md') and any(x in rel.lower() for x in ('dist/','build/','.output/')): risks.append(f'instruction-like file under generated output: {rel}')
    git={}
    if (repo/'.git').exists():
        for key,cmd in {'branch':['git','branch','--show-current'],'status':['git','status','--short'],'root':['git','rev-parse','--show-toplevel']}.items():
            r=subprocess.run(cmd,cwd=repo,text=True,capture_output=True,timeout=30); git[key]=r.stdout.strip() if r.returncode==0 else r.stderr.strip()
    memory={}
    marker=repo/'.agents-memory/PROJECT.json'
    status=repo/'.agents-memory/STATUS.json'
    if marker.is_file():
        memory['project']=read_json(marker)
        memory['status']=read_json(status) if status.is_file() else {}
        memory['handoff_present']=(repo/'.agents-memory/HANDOFF.md').is_file()
    report={'schema_version':1,'repository':str(repo),'git':git,'manifests':sorted(manifests),'instruction_files':sorted(agents),'commands':commands,'risks':risks,'project_memory':memory}
    out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    starter=out.with_name('PROJECT-AGENTS.generated.md')
    lines=['# Project-local AGENTS starter','','> Generated by project_probe.py. Review before installing; it does not replace the universal contract.','','## Canonical target',f'- Repository: `{repo}`',f'- Branch: `{git.get("branch","")}`','','## Project map']
    lines += [f'- `{m}`' for m in sorted(manifests)] or ['- Add canonical subsystem locations.']
    lines += ['','## Project identity and continuity']
    if memory:
        lines += [f"- Project ID: `{memory.get('project',{}).get('project_id','')}`",f"- Remembered canonical root: `{memory.get('project',{}).get('canonical_root','')}`",'- Read and verify `.agents-memory/HANDOFF.md` before mutation.']
    else:
        lines += ['- Run the project-memory identity check before initializing a new memory store.','- Search for prior handoffs, aliases, remotes, artifacts, and similarly named projects; remain read-only if identity is ambiguous.']
    lines += ['','## Exact commands']
    lines += [f'- `{k}` -> `{v}`' for k,v in sorted(commands.items())] or ['- Add setup, build, targeted test, run, package, and deploy commands.']
    lines += ['','## Restricted paths','- Mark generated, vendored, reference, migration, and read-only paths.','','## Known wrong-fix patterns','- Symptom -> tempting wrong fix -> actual owner -> reproducer -> regression check.','','## Runtime verification','- State how to launch the real product and exercise the changed feature.']
    starter.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(out); print(starter); return 0
if __name__=='__main__': raise SystemExit(main())
